name: ramp-stroke
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.23.4
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib-base

  # Extra requirements
  - tensorflow-gpu
  - pytorch
  - cudatoolkit=10.2
  - torchvision
  - keras
  - lightgbm
  - nilearn
  - scikit-image>=0.18

  - pip
  - pip:
    - wheel
    - ramp-workflow
    - git+https://github.com/ramp-kits/stroke_lesions
    - wget
    - ramp-utils
    - imbalanced-learn
    - tensorflow-addons
    - bids
    - osfclient
    # Extra requirements pip
    - xgboost
    - catboost
    - jupyterlab
    - jupyter_contrib_nbextensions
